In [30]:
import pandas as pd
import numpy as np

def get_cost(X, y, theta):
    m = len(y)
    # return (1/(2*m)) * np.square(np.linalg.norm(np.dot(train_x, theta) - train_y))
    return np.square(np.linalg.norm(np.dot(X, theta) - y))


data = pd.read_csv('data/data_set.csv')
print(data)

        AT      V       AP     RH      EP
0    14.96  41.76  1024.07  73.17  463.26
1    25.18  62.96  1020.04  59.08  444.37
2     5.11  39.40  1012.16  92.14  488.56
3    20.86  57.32  1010.24  76.64  446.48
4    10.82  37.50  1009.23  96.62  473.90
..     ...    ...      ...    ...     ...
244  24.78  58.46  1016.82  67.50  442.42
245  23.20  48.41  1008.64  80.92  444.69
246  14.01  39.00  1016.73  79.23  466.70
247  19.40  64.63  1020.38  81.10  453.84
248  30.15  67.32  1013.83  32.80  436.92

[249 rows x 5 columns]


In [31]:
TRAIN_NUM = 5

train_x = np.insert(data.iloc[:TRAIN_NUM,:4].to_numpy(), 0, np.ones(TRAIN_NUM), axis=1)
train_y = data.iloc[:TRAIN_NUM,4:].to_numpy()
# print(train_x)
# print(train_y)

In [32]:
test_x = np.insert(data.iloc[TRAIN_NUM:, :4].to_numpy(), 0, np.ones(249-TRAIN_NUM), axis=1)
test_y = data.iloc[TRAIN_NUM:, 4:].to_numpy()
# print(test_x)
# print(test_y)

In [33]:
theta = np.zeros(5).reshape(5,1)
print(theta)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [34]:
cost = np.square(np.linalg.norm(np.dot(train_x, theta) - train_y))
# tmp = np.dot(train_x, theta) - train_y
# print(tmp)

# print(cost)
# print(get_cost(train_x, train_y, theta))

In [35]:
gradient = (train_x.T).dot(train_x.dot(theta)-train_y)
print(gradient)

[[-2.31657000e+03]
 [-3.50573186e+04]
 [-1.09936020e+05]
 [-2.35151278e+06]
 [-1.85172477e+05]]


In [36]:
for i in range(5):
    # theta -= 0.1 * np.ones(5).reshape(5,1)
    theta =  theta - 0.000001 * (train_x.T).dot(train_x.dot(theta)-train_y)
    print(theta)
    print(train_x.dot(theta)-train_y)

[[2.31657000e-03]
 [3.50573186e-02]
 [1.09936020e-01]
 [2.35151278e+00]
 [1.85172477e-01]]
[[1963.52046997]
 [1973.01372267]
 [1913.121911  ]
 [1950.33903931]
 [1921.71285009]]
[[-7.40513799e-03]
 [-1.15250492e-01]
 [-3.55516207e-01]
 [-7.51796878e+00]
 [-5.86488899e-01]]
[[-8221.67759543]
 [-8172.94135626]
 [-8166.59004602]
 [-8109.1710137 ]
 [-8132.51246726]]
[[3.33977545e-02]
 [5.12422836e-01]
 [1.59393998e+00]
 [3.39040120e+01]
 [2.65766845e+00]]
[[34525.54530031]
 [34409.38407267]
 [34138.05542521]
 [34110.47992541]
 [34065.18047328]]
[[-1.37850891e-01]
 [-2.12508294e+00]
 [-6.59195797e+00]
 [-1.39944059e+02]
 [-1.09525575e+01]]
[[-144884.38024059]
 [-144308.66200548]
 [-143414.22742668]
 [-143085.28813628]
 [-143038.20829506]]
[[5.80879875e-01]
 [8.94135872e+00]
 [2.77601892e+01]
 [5.89695373e+02]
 [4.61749835e+01]]
[[608098.31315717]
 [605770.02198429]
 [601772.0942729 ]
 [600604.53590327]
 [600264.12155521]]
