In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

reader = pd.read_csv('data/data_set.csv', iterator=True)

TRAINING_SIZE = 5

train_data = reader.get_chunk(TRAINING_SIZE).to_numpy()
print(train_data) # ok

[[  14.96   41.76 1024.07   73.17  463.26]
 [  25.18   62.96 1020.04   59.08  444.37]
 [   5.11   39.4  1012.16   92.14  488.56]
 [  20.86   57.32 1010.24   76.64  446.48]
 [  10.82   37.5  1009.23   96.62  473.9 ]]


In [2]:
x, Y = np.split(train_data, (4,), axis=1)
print(x) # ok
print(Y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 [  20.86   57.32 1010.24   76.64]
 [  10.82   37.5  1009.23   96.62]]
[[463.26]
 [444.37]
 [488.56]
 [446.48]
 [473.9 ]]


In [3]:
X = np.insert(x, 0, np.ones(len(x)), axis=1)
print(X)

[[1.00000e+00 1.49600e+01 4.17600e+01 1.02407e+03 7.31700e+01]
 [1.00000e+00 2.51800e+01 6.29600e+01 1.02004e+03 5.90800e+01]
 [1.00000e+00 5.11000e+00 3.94000e+01 1.01216e+03 9.21400e+01]
 [1.00000e+00 2.08600e+01 5.73200e+01 1.01024e+03 7.66400e+01]
 [1.00000e+00 1.08200e+01 3.75000e+01 1.00923e+03 9.66200e+01]]


In [4]:
theta = np.linalg.pinv(np.dot(X.T, X)).dot(X.T).dot(Y)
print(theta)

loss = np.linalg.norm(X.dot(theta)-Y)
print(loss)

[[-2.09864076e+04]
 [-1.41759697e-01]
 [ 1.28294594e+01]
 [ 1.93522239e+01]
 [ 1.50061243e+01]]
8.940356943027699e-06


In [5]:
test_set = reader.get_chunk(500)
test_y = test_set.iloc[:, 4].to_numpy()
print(test_y)

[443.67 467.35 478.42 475.98 477.5  453.02 453.99 440.29 451.28 433.99
 462.19 467.54 477.2  459.85 464.3  468.27 495.24 483.8  443.61 436.06
 443.25 464.16 475.52 484.41 437.89 445.11 438.86 440.98 436.65 444.26
 465.86 444.37 450.69 469.02 448.86 447.14 469.18 482.8  476.7  474.99
 444.22 461.33 448.06 474.6  473.05 432.06 467.41 430.12 473.62 471.81
 442.99 442.77 491.49 447.46 446.11 442.44 446.22 471.49 463.5  440.01
 441.03 452.68 474.91 478.77 434.2  437.91 477.61 431.65 430.57 481.09
 445.56 475.74 435.12 446.15 436.64 436.69 468.75 466.6  465.48 441.34
 441.83 464.7  437.99 459.12 429.69 459.8  433.63 442.84 485.13 459.12
 445.31 480.8  432.55 443.86 449.77 470.71 452.17 478.29 428.54 478.27
 439.58 457.32 475.51 439.66 471.99 479.81 434.78 446.58 437.76 459.36
 462.28 464.33 444.36 438.64 470.49 455.13 450.22 440.43 482.98 460.44
 444.97 433.94 439.73 434.48 442.33 457.67 454.66 432.21 457.66 435.21
 448.22 475.51 446.53 441.3  433.54 472.52 474.77 435.1  450.74 442.7
 426.56

In [6]:
test_x = np.insert(test_set.iloc[:, :4].to_numpy(), 0, np.ones(len(test_set)), axis=1)
print(test_x)

[[1.00000e+00 2.62700e+01 5.94400e+01 1.01223e+03 5.87700e+01]
 [1.00000e+00 1.58900e+01 4.39600e+01 1.01402e+03 7.52400e+01]
 [1.00000e+00 9.48000e+00 4.47100e+01 1.01912e+03 6.64300e+01]
 ...
 [1.00000e+00 1.40100e+01 3.90000e+01 1.01673e+03 7.92300e+01]
 [1.00000e+00 1.94000e+01 6.46300e+01 1.02038e+03 8.11000e+01]
 [1.00000e+00 3.01500e+01 6.73200e+01 1.01383e+03 3.28000e+01]]


In [7]:
test_pred = test_x.dot(theta)

In [8]:
# plt.figure(figsize=(8, 4))  # figsize:确定画布大小 

# plt.scatter(test_pred, test_y, c="blue", label = 'test data' )
# plt.scatter(X.dot(theta), Y, c='red', label='training data') 

# t = np.linspace(400, 500, 200)
# plt.plot(t, t, 'r', label='y=x')
# plt.xlabel(u'predicted value', fontsize=18)
# plt.ylabel(u'true value', fontsize=18)

# plt.legend()  # 显示图例

# plt.show()  # 显示所绘图形

In [9]:
test_pred_mean = np.mean(test_pred)
# print(test_pred_mean)

# test_pred_mean_arr = np.full_like(test_pred, test_pred_mean)

_var = np.square(np.linalg.norm(test_pred - test_pred_mean))

bias = np.square(np.linalg.norm(test_y - test_pred_mean))
# print(test_pred_mean_arr)
# print(test_y.flatten())
print(_var)
print(bias)

3599848042.7098727
218290658.79888767
